import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Navigation from "../components/Navigation.js";
import Link from "next/link";
import { Col, Container, Row } from "react-bootstrap";
import login_img from "../Images/login.webp";
import Facebook_icon from "../Images/facebook-circled.png";
import Google_icon from "../Images/google-logo.png";
import LoginImage from "../Images/login.svg"
import Footer from "../components/Footer";

export default function Home() {
  return (
    <div className="login_section">
      <div className="">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

          <Navigation />
        <main
        style={{backgroundImage:`url("https://images.unsplash.com/photo-1613864601020-ec7288d0a9db?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1331&q=80")`}}
        
        className="pt-28 md:pt-24 bg-black min-h-screen text-gray-50 bg-no-repeat bg-cover">
          
            <div className="px-5 md:px-0 md:container md:mx-auto flex items-center justify-center">
          <div className="w-full md:max-w-sm bg-black/50 h-96 py-3 mt-10 rounded">
            <h2 className="font-semibold text-2xl text-center py-2 ">Login</h2>
            <form className="px-8 space-y-3">
              <div className="w-full h-10 bg-gray-900 rounded flex items-center">
              <input type="email" placeholder="Email" className="bg-transparent w-full px-2 focus:outline-none" />
              </div>
              <div className="w-full h-10 bg-gray-900 rounded flex items-center">
              <input type="password" placeholder="password" className="bg-transparent w-full px-2 focus:outline-none" />
              </div>
              <button className="w-full bg-blue-500 h-10 font-medium text-lg rounded">Login</button>
            </form>
            <p className="text-center py-3 text-gray-500">
              OR</p>
            <div className="px-8 space-y-3">
            <button className="flex items-center space-x-2">
            <Image
              className=""
              height={30}
              width={30}
              src={Facebook_icon}
              alt=""
            />
            <span className="text-gray-500 font-semibold text-sm">Login with facebook</span>
            </button>
            <button className="flex items-center space-x-2">

           <Image
              className=""
              height={30}
              width={30}
              src={Google_icon}
              alt=""
            />
            <span className="text-gray-500 font-semibold text-sm">Login with Google</span>

           </button>
            </div>
         
          </div>
          </div>
          
        </main>

        <Footer />

      
      </div>
    </div>
  );
}


{/* <div className="login_form_full_area">
<Container>
  <Row className="row">
    <Col className="col-lg-6 col-md-6- col-sm-12 py-2">
      <div className="">
        <Image
          className="inner_login_img"
          height={620}
          src={login_img}
          alt=""
        />
      </div>
    </Col>
    <Col className="col-lg-6 col-md-6- col-sm-12 py-2">
      <form>
        <div className="inner_login_from">
          <h2>Login to Your Account</h2>
          <p>Login using social networks</p>
          <div className="login_with_social_icon">
            {/* <i class="fa-brands fa-facebook-f"></i>
          <i class="fa-brands fa-google"></i> */}
//             <Image
//               className="inner_login_img"
//               height={30}
//               width={30}
//               src={Facebook_icon}
//               alt=""
//             />
//             <Image
//               className="inner_login_img"
//               height={30}
//               width={30}
//               src={Google_icon}
//               alt=""
//             />
//           </div>
//           <p>------------------or------------------</p>
//           <input type="email" placeholder="Email" />
//           <input type="password" placeholder="Password" />
//           <button>Login</button>
//           <p className="register_link">
//             Are you new ? please{" "}
//             <Link href="/signUp">Register</Link> to view all content
//           </p>
//         </div>
//       </form>
//     </Col>
//   </Row>
// </Container>
// </div> */}