import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Navigation from "../components/Navigation.js";
import Link from "next/link";
import { Col, Container, Row } from "react-bootstrap";
import register_img from "../Images/register.webp";
import Facebook_icon from "../Images/facebook-circled.png";
import Google_icon from "../Images/google-logo.png";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <Navigation />
        <main
        style={{backgroundImage:`url("https://images.unsplash.com/photo-1613864601020-ec7288d0a9db?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1331&q=80")`}}
        
        className="pt-28 md:pt-24 bg-black min-h-screen text-gray-50 bg-no-repeat bg-cover">
          
            <div className="px-5 md:px-0 md:container md:mx-auto flex items-center justify-center">
          <div className="w-full md:max-w-sm bg-black/50 h-96 py-3 mt-10 rounded">
            <h2 className="font-semibold text-2xl text-center py-2 ">Register Now</h2>
        
            <form className="px-8 space-y-3">
              <div className="w-full h-10 bg-gray-900 rounded flex items-center">
              <input type="email" placeholder="Email" className="bg-transparent w-full px-2 focus:outline-none" />
              </div>
              <div className="w-full h-10 bg-gray-900 rounded flex items-center">
              <input type="password" placeholder="password" className="bg-transparent w-full px-2 focus:outline-none" />
              </div>
              <button className="w-full bg-blue-500 h-10 font-medium text-lg rounded">Signup</button>
              <p className="text-gray-400 text-xs">
            Already register ? Please <Link href="/login"><a className="text-blue-500">
            Login</a></Link>
          </p>
            </form>
            <p className="text-center py-3 text-gray-500">
              OR</p>
            <div className="px-8 space-y-3">
            <button className="flex items-center space-x-2">
            <Image
              className=""
              height={30}
              width={30}
              src={Facebook_icon}
              alt=""
            />
            <span className="text-gray-500 font-semibold text-sm">Login with facebook</span>
            </button>
            <button className="flex items-center space-x-2">

           <Image
              className=""
              height={30}
              width={30}
              src={Google_icon}
              alt=""
            />
            <span className="text-gray-500 font-semibold text-sm">Login with Google</span>

           </button>
            </div>
            </div>
            
          </div>
          
        </main>

      <footer className={styles.footer}>
   
      </footer>
    </div>
  );
}
