import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navigation from '../components/Navigation.js'
import ReactPlayer from 'react-player'
import React from 'react'
import like_icon from "../Images/like.png";
import dislike_icon from "../Images/dislike.png";
import shear_icon from "../Images/shear.png";
import { ThumbDownIcon, ThumbUpIcon, ShareIcon } from '@heroicons/react/outline'
import Footer from "../components/Footer"


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>FART.XXX</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <Navigation />
        <main className="flex flex-col items-center bg-black min-h-screen pt-28 md:pt-24">
        <div className="px-3 md:px-0 md:container md:mx-auto text-gray-50">
          <ReactPlayer
            url={"https://www.youtube.com/watch?v=Zv11L-ZfrSg"}
            width="100%"
            height="600px"
            playIcon="true"
          />
          {/* <h1>Page 1</h1> */}
         
            <div className=" mt-2 flex flex-col md:flex-row justify-between">
              <div className="space-y-2">
              <h2 className="text-5xl font-medium">Shiela Star</h2>
              <p className=" text-gray-400 text-sm">1/11/2022</p>
              </div>


             <div>
             <div className="flex justify-center space-x-2 my-3">
                <button className="bg-blue-500 text-white px-4 py-1">480p</button>
              <button className="bg-blue-500 text-white px-4 py-1">720p</button>
              <button className="bg-blue-500 text-white px-4 py-1">1080p</button>
              </div>
              <div className="flex items-center justify-end space-x-4 pt-4">
                <ThumbUpIcon className="w-6 h-6 cursor-pointer" />
                <ThumbDownIcon className="w-6 h-6 cursor-pointer" />
                <ShareIcon className="w-6 h-6 cursor-pointer"/>
              </div></div>
            
            </div>
          
            <div className="grid grid-cols-4 md:grid-cols-6 lg:flex lg:justify-center gap-3 mt-5">

              <button className="px-2 py-1 bg-gray-600">new</button>
              <button className="px-2 py-1 bg-gray-600">old</button>
              <button className="px-2 py-1 bg-gray-600">favorite</button>
              <button className="px-2 py-1 bg-gray-600">action</button>
              <button className="px-2 py-1 bg-gray-600">farting</button>
              <button className="px-2 py-1 bg-gray-600">ebony</button>
              <button className="px-2 py-1 bg-gray-600">blonde</button>
              <button className="px-2 py-1 bg-gray-600">brunette</button>
              <button className="px-2 py-1 bg-gray-600">college</button>
              <button className="px-2 py-1 bg-gray-600">asian</button>
              <button className="px-2 py-1 bg-gray-600">skinny</button>
              <button className="px-2 py-1 bg-gray-600">1080p</button>
              <button className="px-2 py-1 bg-gray-600">newby</button>
              <button className="px-2 py-1 bg-gray-600">model</button>
              <button className="px-2 py-1 bg-gray-600">Indian</button>
            </div>
          
        </div>
      </main>
     <Footer />
    </div>
  )
}
